#!/bin/bash

usage()
{
    echo "envwarden: use Bitwarden to manage server secrets"
    echo ""
    echo "Get your secure environment variables from Bitwarden onto your server."
    echo "envwarden searches your Bitwarden vault for items matching"
    echo "a search criteria (defaults to 'envwarden')."
    echo "Then it goes through all custom fields on every item found"
    echo "and make them available as envirnoment variables."
    echo ""
    echo "Usage: envwarden [--help] [--search] [--dotenv] [--copy]"
    echo ""
    echo "To export environment variables, use: \`eval \$(envwarden)\`"
    echo "To create an .env file, use: \`envwarden --dotenv > .env\`"
    echo ""
    echo "Options:"
    echo -e "\t-h --help"
    echo -e "\t-o --organizationid <organization-id> define the filter for organization scoped secrets"
    echo -e "\t-l --collectionid <collection-id> define the filter for collection scoped secrets"
    echo -e "\t-d --dotenv (optional) outputs secrets to stdout in .env format"
    echo -e "\t-k --dotenv-docker (optional) outputs secrets to stdout in a \"docker-friendly\" .env format (no quotes)"
    echo -e "\t-c --copy <destination folder> (optional) copies all attachments on the item to a folder"
    echo -e "\t-g --github envs to github actions"
    echo ""
    echo "You can use ~/.envwarden to store your credentials (just email, or email:password)"
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h | --help)
            usage
            exit
            ;;
        -d | --dotenv)
            DOTENV=true
            ;;
        -g | --github)
            GITHUB_ACTIONS=true
            ;;
        -k | --dotenv-docker)
            DOTENV_DOCKER=true
            ;;
        -o | --organizationid)
            BW_ORGANIZATIONID=$2
            shift
            ;;
        -l | --collectionid)
            BW_COLLECTIONID=$2
            shift
            ;;
        -c | --copy)
            COPY_TO=$2
            COPY_TO=${COPY_TO:=.}
            shift
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

bw logout > /dev/null
export BW_SESSION
bw login --apikey
BW_SESSION="$(bw unlock "$BW_PASSWORD" --raw)"

if ! bw sync > /dev/null; then
    (>&2 echo "unable to login or sync with bitwarden.")
    exit 1
fi

echo ""

while read -r key; do
    read -r value
    if [[ -n "$DOTENV" ]]; then
        echo "$key=\"$value\""
    elif [[ -n "$DOTENV_DOCKER" ]]; then
        echo "$key=$value"
     elif [[ -n "$GITHUB_ACTIONS" ]]; then
        echo "::add-mask::$value"
        echo "::set-output name=$key::$value"
    else
        # wrap keys and values in single quotes to avoid further interpolation,
        # plus sanitize for single quote symbols to avoid command injection
        quoted_key="$(echo "$key" | sed "s/'/'\"'\"'/g")"
        quoted_value="$(echo "$value" | sed "s/'/'\"'\"'/g")"
        echo export \'$quoted_key\'=\'$quoted_value\'
    fi
done < <(bw list items --organizationid "$BW_ORGANIZATIONID" --collectionid "$BW_COLLECTIONID" |jq -r '.[].fields[]? | select(.name != null) | select(.value != null) | .name, .value')

if [[ -n "$COPY_TO" ]]; then
    item_id=$(bw list items --organizationid "$BW_ORGANIZATIONID" --collectionid "$BW_COLLECTIONID" |jq -r '.[].id')
    if [[ -n "$item_id" ]]; then
        while read -r attachment_id; do
            read -r filename
            bw get attachment "$attachment_id" --itemid "$item_id" --output "$COPY_TO/$filename" 1>&2
        done < <(bw list items --organizationid "$BW_ORGANIZATIONID" --collectionid "$BW_COLLECTIONID" |jq -r '.[].attachments[] | .id, .fileName')
    fi
fi
