name: Unstable release channel (unstable.yml)

on:
  push:
    branches:
      - main

jobs:

  push_to_registry:
  
      name: Push Docker image to GitHub Packages
      runs-on: ubuntu-latest

      steps:

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Packages
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.GH_PAT_USER }}
            password: ${{ secrets.GH_PAT }}

        - name: Check out the reposiotry
          uses: actions/checkout@v2

        - name: Push to GitHub Packages
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            context: "."
            platforms: linux/amd64,linux/arm64
            tags: |
              metacron/envwarden:latest
              metacron/envwarden:unstable
        
        - name: Image digest (metacron/envwarden:unstable)
          run: echo ${{ steps.docker_build.outputs.digest }}